### ISSUE TITLE
Second-level menu shortcut key display is too dark to see

### ISSUE THREAD

**Issue by tkna91** [themix-project/oomox-gtk-theme#88]
The shortcut keys (in this case "Space") in Audacity's submenu displays (e.g. "Transport->Playing->Play/Stop Space") are too dark to see.
The non "Inverse GUI Variant" is visible.

https://user-images.githubusercontent.com/102382754/204089508-2e31a2c0-1aac-4d59-8a54-4247c3eb09cc.mp4

```
$ pacman -Qsq themix | xargs pacman -Q
themix-export-spotify-git 1.2.6.r1.gf47c36b-1
themix-full-git 1.15-2
themix-gui-git 1.15.r28.ga78cc920-1
themix-icons-archdroid-git 1.0.3.r0.gb90779de4-1
themix-icons-gnome-colors-git 5.5.6.r0.gd2cb7eb-2
themix-icons-numix-git 22.11.17.r1.g97e19b3d5.e6197dd14-1
themix-icons-papirus-git 20221101.r10.g6fe16ea79b-1
themix-icons-suru-plus-aspromauros-git 3.0.r0.gd43a8ec4-2
themix-icons-suru-plus-git 30.0.r2.g9bd895f32-2
themix-import-images-git 1.15.r28.ga78cc920-1
themix-plugin-base16-git 1.5.1.r8.g77f0bfa-1
themix-theme-oomox-git 1.12.3.r1.ge87724dd-1
$ pacman -Q audacity sway-im-git wlroots-git linux
audacity 1:3.2.1-2
sway-im-git r7015.94b69acf-1
wlroots-git 0.17.0.r5941.c02872e0-1
linux 6.0.9.arch1-1
$ 
```

**Comment by actionless** [comment]
i've moved the issue to according repository

**Comment by actionless** [comment]
this is quite interesting situation :)

i did some debugging: that's a bug in gtk3 itself:

when menuitem's accelerator is hovered it have such css selector:

`.context-menu menuitem:hover accelerator`

when it's not:

`.context-menu menuitem accelerator`

hovewever in 2nd-level menus `accelerator` element always have hover status:

`.context-menu menuitem:hover accelerator`

________________________________________________________________________________________________________

because of that accelerator (hotkey)  foreground color is always same as "Selection Foreground Color", half-transparent (because that's how it should like when it is hovered by mouse cursor)

and as a side-effect of that, because of dark theme - half-transparent color became less visible

the only thing which i can fix here is change color-mixing there from half-transparent to mix of fg/bg, so in dark themes it will be a bit more contrast - because of aforementioned gtk3 bug this would be still looking incorrectly, however it will be at least readable:

**Comment by tkna91** [comment]
Thank you, even in Base16, I brightened the "Selected Text" and now I can see it!

https://user-images.githubusercontent.com/102382754/204122086-8f7ba844-2a5b-46c4-9c08-9d47275746eb.mp4

https://streamable.com/9pcdum (same video)

Should I ask the following upstream to solve the problem you mentioned?
https://gitlab.gnome.org/GNOME/gtk/-/issues

**Comment by actionless** [comment]
> Should I ask the following upstream to solve the problem you mentioned?
> https://gitlab.gnome.org/GNOME/gtk/-/issues

yes, but i don't think they gon fix it due to gtk4 development

**Comment by actionless** [comment]
speaking of accelerators, that reminded me a moment when i lost all human respect to people from gtk:

they removed displaying of hotkeys on MenuItems themselves (mnemonics), by simply hardcoding the setting which was configurable before:

https://www.reddit.com/r/gnome/comments/2xnhg9/is_there_any_way_to_force_always_show_mnemonics/

such people don't deserve to be called programmists or even humans in general
